name: reusable-workflow
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the deplyable artifact file
                required: false
                default: dist
                type: string

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/download-artifact@v3
              with:
                name: ${{inputs.artifact-name}}
            - name: output information
              run: echo "deploying and uploading..."
